// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

#nullable disable

namespace RpgApi.Migrations
{
    [DbContext(typeof(RpgContext))]
    partial class RpgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ClassSkill", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("ClassSkill");
                });

            modelBuilder.Entity("EnemyClassSkill", b =>
                {
                    b.Property<int>("EnemyClassesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnemyClassesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("EnemyClassSkill");
                });

            modelBuilder.Entity("RpgApi.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Magic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaRegen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RpgApi.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseAgility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCharisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseEndurance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseIntelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseLuck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseStrength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseWisdom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("RpgApi.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnemyClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Magic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyClassId");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("RpgApi.Models.EnemyClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseAgility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseCharisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseEndurance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseIntelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseLuck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseStrength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseWisdom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EnemyClasses");
                });

            modelBuilder.Entity("RpgApi.Models.FightMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FightSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FightSessionId");

                    b.ToTable("FightMoves");
                });

            modelBuilder.Entity("RpgApi.Models.FightSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterActivePassiveSkillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterAttack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterCooldownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterCurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterCurrentMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterCurrentStamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterHealthRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterManaRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterMaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterMaxMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterMaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacterSkillIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterStaminaRegen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyActivePassiveSkillsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnemyAttack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyCooldownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnemyCurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyCurrentMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyCurrentStamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyHealthRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyManaRegen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyMaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyMaxMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyMaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnemySkillIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnemyStaminaRegen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVictory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActionAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LockedByPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("FightSessions");
                });

            modelBuilder.Entity("RpgApi.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RpgApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgilityModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackPower")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharismaModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefensePower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EnduranceModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnemyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntelligenceModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LuckModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagicPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredAgility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredCharisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredEndurance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredIntelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredLuck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredStrength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredWisdom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrengthModifier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WisdomModifier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EnemyId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ClassSkill", b =>
                {
                    b.HasOne("RpgApi.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgApi.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnemyClassSkill", b =>
                {
                    b.HasOne("RpgApi.Models.EnemyClass", null)
                        .WithMany()
                        .HasForeignKey("EnemyClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgApi.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RpgApi.Models.Character", b =>
                {
                    b.HasOne("RpgApi.Models.Class", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RpgApi.Models.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RpgApi.Models.Enemy", b =>
                {
                    b.HasOne("RpgApi.Models.EnemyClass", "EnemyClass")
                        .WithMany("Enemies")
                        .HasForeignKey("EnemyClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnemyClass");
                });

            modelBuilder.Entity("RpgApi.Models.FightMove", b =>
                {
                    b.HasOne("RpgApi.Models.FightSession", "FightSession")
                        .WithMany("Moves")
                        .HasForeignKey("FightSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FightSession");
                });

            modelBuilder.Entity("RpgApi.Models.Skill", b =>
                {
                    b.HasOne("RpgApi.Models.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId");

                    b.HasOne("RpgApi.Models.Enemy", null)
                        .WithMany("Skills")
                        .HasForeignKey("EnemyId");
                });

            modelBuilder.Entity("RpgApi.Models.Character", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("RpgApi.Models.Class", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("RpgApi.Models.Enemy", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("RpgApi.Models.EnemyClass", b =>
                {
                    b.Navigation("Enemies");
                });

            modelBuilder.Entity("RpgApi.Models.FightSession", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("RpgApi.Models.Player", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
